### ISSUE TITLE
Exlir 0.13.3-dev issues

### ISSUE THREAD

**Issue by rambocoder** [meh/jazz#6]
``` elixir
JSON.encode!([name: "David", surname: "Davidson"])
```

produces:

*\* (FunctionClauseError) no function clause matching in Jazz.Encoder.Any.to_json/2
      (jazz) lib/jazz/encoder.ex:115: Jazz.Encoder.Any.to_json({:name, "David"}, [])
      (jazz) lib/jazz/encoder.ex:12: Jazz.Encode.it/2
      (jazz) lib/jazz.ex:18: Jazz.encode!/2
      (jazz) lib/jazz/encoder.ex:73: anonymous fn/2 in Jazz.Encoder.List.encode/3
    (elixir) lib/enum.ex:962: Enum."-map/2-lc$^0/1-0-"/2
      (jazz) lib/jazz/encoder.ex:72: Jazz.Encoder.List.encode/3
      (jazz) lib/jazz/encoder.ex:60: Jazz.Encoder.List.to_json/2
      (jazz) lib/jazz/encoder.ex:12: Jazz.Encode.it/2

**Comment by rambocoder** [comment]
It is actually just README.md documentaton that needs to be updated.
